# Copyright Contributors to Agones a Series of LF Projects, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This code was autogenerated. Do not edit directly.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import beta_pb2 as beta__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in beta_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SDKStub(object):
    """SDK service to be used in the GameServer SDK to the Pod Sidecar
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCounter = channel.unary_unary(
                '/agones.dev.sdk.beta.SDK/GetCounter',
                request_serializer=beta__pb2.GetCounterRequest.SerializeToString,
                response_deserializer=beta__pb2.Counter.FromString,
                _registered_method=True)
        self.UpdateCounter = channel.unary_unary(
                '/agones.dev.sdk.beta.SDK/UpdateCounter',
                request_serializer=beta__pb2.UpdateCounterRequest.SerializeToString,
                response_deserializer=beta__pb2.Counter.FromString,
                _registered_method=True)
        self.GetList = channel.unary_unary(
                '/agones.dev.sdk.beta.SDK/GetList',
                request_serializer=beta__pb2.GetListRequest.SerializeToString,
                response_deserializer=beta__pb2.List.FromString,
                _registered_method=True)
        self.UpdateList = channel.unary_unary(
                '/agones.dev.sdk.beta.SDK/UpdateList',
                request_serializer=beta__pb2.UpdateListRequest.SerializeToString,
                response_deserializer=beta__pb2.List.FromString,
                _registered_method=True)
        self.AddListValue = channel.unary_unary(
                '/agones.dev.sdk.beta.SDK/AddListValue',
                request_serializer=beta__pb2.AddListValueRequest.SerializeToString,
                response_deserializer=beta__pb2.List.FromString,
                _registered_method=True)
        self.RemoveListValue = channel.unary_unary(
                '/agones.dev.sdk.beta.SDK/RemoveListValue',
                request_serializer=beta__pb2.RemoveListValueRequest.SerializeToString,
                response_deserializer=beta__pb2.List.FromString,
                _registered_method=True)


class SDKServicer(object):
    """SDK service to be used in the GameServer SDK to the Pod Sidecar
    """

    def GetCounter(self, request, context):
        """Gets a Counter. Returns NOT_FOUND if the Counter does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCounter(self, request, context):
        """UpdateCounter returns the updated Counter. Returns NOT_FOUND if the Counter does not exist (name cannot be updated).
        Returns OUT_OF_RANGE if the Count is out of range [0,Capacity].
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetList(self, request, context):
        """Gets a List. Returns NOT_FOUND if the List does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateList(self, request, context):
        """UpdateList returns the updated List. Returns NOT_FOUND if the List does not exist (name cannot be updated).
        **THIS WILL OVERWRITE ALL EXISTING LIST.VALUES WITH ANY REQUEST LIST.VALUES**
        Use AddListValue() or RemoveListValue() for modifying the List.Values field.
        Returns INVALID_ARGUMENT if the field mask path(s) are not field(s) of the List.
        If a field mask path(s) is specified, but the value is not set in the request List object,
        then the default value for the variable will be set (i.e. 0 for "capacity", empty list for "values").
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddListValue(self, request, context):
        """Adds a value to a List and returns updated List. Returns NOT_FOUND if the List does not exist.
        Returns ALREADY_EXISTS if the value is already in the List.
        Returns OUT_OF_RANGE if the List is already at Capacity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveListValue(self, request, context):
        """Removes a value from a List and returns updated List. Returns NOT_FOUND if the List does not exist.
        Returns NOT_FOUND if the value is not in the List.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDKServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCounter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCounter,
                    request_deserializer=beta__pb2.GetCounterRequest.FromString,
                    response_serializer=beta__pb2.Counter.SerializeToString,
            ),
            'UpdateCounter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCounter,
                    request_deserializer=beta__pb2.UpdateCounterRequest.FromString,
                    response_serializer=beta__pb2.Counter.SerializeToString,
            ),
            'GetList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetList,
                    request_deserializer=beta__pb2.GetListRequest.FromString,
                    response_serializer=beta__pb2.List.SerializeToString,
            ),
            'UpdateList': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateList,
                    request_deserializer=beta__pb2.UpdateListRequest.FromString,
                    response_serializer=beta__pb2.List.SerializeToString,
            ),
            'AddListValue': grpc.unary_unary_rpc_method_handler(
                    servicer.AddListValue,
                    request_deserializer=beta__pb2.AddListValueRequest.FromString,
                    response_serializer=beta__pb2.List.SerializeToString,
            ),
            'RemoveListValue': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveListValue,
                    request_deserializer=beta__pb2.RemoveListValueRequest.FromString,
                    response_serializer=beta__pb2.List.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agones.dev.sdk.beta.SDK', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agones.dev.sdk.beta.SDK', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SDK(object):
    """SDK service to be used in the GameServer SDK to the Pod Sidecar
    """

    @staticmethod
    def GetCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.beta.SDK/GetCounter',
            beta__pb2.GetCounterRequest.SerializeToString,
            beta__pb2.Counter.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.beta.SDK/UpdateCounter',
            beta__pb2.UpdateCounterRequest.SerializeToString,
            beta__pb2.Counter.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.beta.SDK/GetList',
            beta__pb2.GetListRequest.SerializeToString,
            beta__pb2.List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.beta.SDK/UpdateList',
            beta__pb2.UpdateListRequest.SerializeToString,
            beta__pb2.List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddListValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.beta.SDK/AddListValue',
            beta__pb2.AddListValueRequest.SerializeToString,
            beta__pb2.List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveListValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.beta.SDK/RemoveListValue',
            beta__pb2.RemoveListValueRequest.SerializeToString,
            beta__pb2.List.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)