# Copyright Contributors to Agones a Series of LF Projects, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This code was autogenerated. Do not edit directly.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alpha.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'alpha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lpha.proto\x12\x14\x61gones.dev.sdk.alpha\"\x07\n\x05\x45mpty\"\x16\n\x05\x43ount\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"\x14\n\x04\x42ool\x12\x0c\n\x04\x62ool\x18\x01 \x01(\x08\"\x1c\n\x08PlayerID\x12\x10\n\x08playerID\x18\x01 \x01(\t\"\x1c\n\x0cPlayerIDList\x12\x0c\n\x04list\x18\x01 \x03(\t2\xc3\x04\n\x03SDK\x12M\n\rPlayerConnect\x12\x1e.agones.dev.sdk.alpha.PlayerID\x1a\x1a.agones.dev.sdk.alpha.Bool\"\x00\x12P\n\x10PlayerDisconnect\x12\x1e.agones.dev.sdk.alpha.PlayerID\x1a\x1a.agones.dev.sdk.alpha.Bool\"\x00\x12O\n\x11SetPlayerCapacity\x12\x1b.agones.dev.sdk.alpha.Count\x1a\x1b.agones.dev.sdk.alpha.Empty\"\x00\x12O\n\x11GetPlayerCapacity\x12\x1b.agones.dev.sdk.alpha.Empty\x1a\x1b.agones.dev.sdk.alpha.Count\"\x00\x12L\n\x0eGetPlayerCount\x12\x1b.agones.dev.sdk.alpha.Empty\x1a\x1b.agones.dev.sdk.alpha.Count\"\x00\x12Q\n\x11IsPlayerConnected\x12\x1e.agones.dev.sdk.alpha.PlayerID\x1a\x1a.agones.dev.sdk.alpha.Bool\"\x00\x12X\n\x13GetConnectedPlayers\x12\x1b.agones.dev.sdk.alpha.Empty\x1a\".agones.dev.sdk.alpha.PlayerIDList\"\x00\x42\tZ\x07./alphab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alpha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./alpha'
  _globals['_EMPTY']._serialized_start=37
  _globals['_EMPTY']._serialized_end=44
  _globals['_COUNT']._serialized_start=46
  _globals['_COUNT']._serialized_end=68
  _globals['_BOOL']._serialized_start=70
  _globals['_BOOL']._serialized_end=90
  _globals['_PLAYERID']._serialized_start=92
  _globals['_PLAYERID']._serialized_end=120
  _globals['_PLAYERIDLIST']._serialized_start=122
  _globals['_PLAYERIDLIST']._serialized_end=150
  _globals['_SDK']._serialized_start=153
  _globals['_SDK']._serialized_end=732
# @@protoc_insertion_point(module_scope)