# Copyright Contributors to Agones a Series of LF Projects, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This code was autogenerated. Do not edit directly.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import alpha_pb2 as alpha__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in alpha_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SDKStub(object):
    """SDK service to be used in the GameServer SDK to the Pod Sidecar.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayerConnect = channel.unary_unary(
                '/agones.dev.sdk.alpha.SDK/PlayerConnect',
                request_serializer=alpha__pb2.PlayerID.SerializeToString,
                response_deserializer=alpha__pb2.Bool.FromString,
                _registered_method=True)
        self.PlayerDisconnect = channel.unary_unary(
                '/agones.dev.sdk.alpha.SDK/PlayerDisconnect',
                request_serializer=alpha__pb2.PlayerID.SerializeToString,
                response_deserializer=alpha__pb2.Bool.FromString,
                _registered_method=True)
        self.SetPlayerCapacity = channel.unary_unary(
                '/agones.dev.sdk.alpha.SDK/SetPlayerCapacity',
                request_serializer=alpha__pb2.Count.SerializeToString,
                response_deserializer=alpha__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPlayerCapacity = channel.unary_unary(
                '/agones.dev.sdk.alpha.SDK/GetPlayerCapacity',
                request_serializer=alpha__pb2.Empty.SerializeToString,
                response_deserializer=alpha__pb2.Count.FromString,
                _registered_method=True)
        self.GetPlayerCount = channel.unary_unary(
                '/agones.dev.sdk.alpha.SDK/GetPlayerCount',
                request_serializer=alpha__pb2.Empty.SerializeToString,
                response_deserializer=alpha__pb2.Count.FromString,
                _registered_method=True)
        self.IsPlayerConnected = channel.unary_unary(
                '/agones.dev.sdk.alpha.SDK/IsPlayerConnected',
                request_serializer=alpha__pb2.PlayerID.SerializeToString,
                response_deserializer=alpha__pb2.Bool.FromString,
                _registered_method=True)
        self.GetConnectedPlayers = channel.unary_unary(
                '/agones.dev.sdk.alpha.SDK/GetConnectedPlayers',
                request_serializer=alpha__pb2.Empty.SerializeToString,
                response_deserializer=alpha__pb2.PlayerIDList.FromString,
                _registered_method=True)


class SDKServicer(object):
    """SDK service to be used in the GameServer SDK to the Pod Sidecar.
    """

    def PlayerConnect(self, request, context):
        """PlayerConnect increases the SDK’s stored player count by one, and appends this playerID to GameServer.Status.Players.IDs.

        GameServer.Status.Players.Count and GameServer.Status.Players.IDs are then set to update the player count and id list a second from now,
        unless there is already an update pending, in which case the update joins that batch operation.

        PlayerConnect returns true and adds the playerID to the list of playerIDs if this playerID was not already in the
        list of connected playerIDs.

        If the playerID exists within the list of connected playerIDs, PlayerConnect will return false, and the list of
        connected playerIDs will be left unchanged.

        An error will be returned if the playerID was not already in the list of connected playerIDs but the player capacity for
        the server has been reached. The playerID will not be added to the list of playerIDs.

        Warning: Do not use this method if you are manually managing GameServer.Status.Players.IDs and GameServer.Status.Players.Count
        through the Kubernetes API, as indeterminate results will occur.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayerDisconnect(self, request, context):
        """Decreases the SDK’s stored player count by one, and removes the playerID from GameServer.Status.Players.IDs.

        GameServer.Status.Players.Count and GameServer.Status.Players.IDs are then set to update the player count and id list a second from now,
        unless there is already an update pending, in which case the update joins that batch operation.

        PlayerDisconnect will return true and remove the supplied playerID from the list of connected playerIDs if the
        playerID value exists within the list.

        If the playerID was not in the list of connected playerIDs, the call will return false, and the connected playerID list
        will be left unchanged.

        Warning: Do not use this method if you are manually managing GameServer.status.players.IDs and GameServer.status.players.Count
        through the Kubernetes API, as indeterminate results will occur.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPlayerCapacity(self, request, context):
        """Update the GameServer.Status.Players.Capacity value with a new capacity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerCapacity(self, request, context):
        """Retrieves the current player capacity. This is always accurate from what has been set through this SDK,
        even if the value has yet to be updated on the GameServer status resource.

        If GameServer.Status.Players.Capacity is set manually through the Kubernetes API, use SDK.GameServer() or SDK.WatchGameServer() instead to view this value.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerCount(self, request, context):
        """Retrieves the current player count. This is always accurate from what has been set through this SDK,
        even if the value has yet to be updated on the GameServer status resource.

        If GameServer.Status.Players.Count is set manually through the Kubernetes API, use SDK.GameServer() or SDK.WatchGameServer() instead to view this value.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsPlayerConnected(self, request, context):
        """Returns if the playerID is currently connected to the GameServer. This is always accurate from what has been set through this SDK,
        even if the value has yet to be updated on the GameServer status resource.

        If GameServer.Status.Players.IDs is set manually through the Kubernetes API, use SDK.GameServer() or SDK.WatchGameServer() instead to determine connected status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectedPlayers(self, request, context):
        """Returns the list of the currently connected player ids. This is always accurate from what has been set through this SDK,
        even if the value has yet to be updated on the GameServer status resource.

        If GameServer.Status.Players.IDs is set manually through the Kubernetes API, use SDK.GameServer() or SDK.WatchGameServer() instead to view this value.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDKServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayerConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayerConnect,
                    request_deserializer=alpha__pb2.PlayerID.FromString,
                    response_serializer=alpha__pb2.Bool.SerializeToString,
            ),
            'PlayerDisconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayerDisconnect,
                    request_deserializer=alpha__pb2.PlayerID.FromString,
                    response_serializer=alpha__pb2.Bool.SerializeToString,
            ),
            'SetPlayerCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPlayerCapacity,
                    request_deserializer=alpha__pb2.Count.FromString,
                    response_serializer=alpha__pb2.Empty.SerializeToString,
            ),
            'GetPlayerCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerCapacity,
                    request_deserializer=alpha__pb2.Empty.FromString,
                    response_serializer=alpha__pb2.Count.SerializeToString,
            ),
            'GetPlayerCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerCount,
                    request_deserializer=alpha__pb2.Empty.FromString,
                    response_serializer=alpha__pb2.Count.SerializeToString,
            ),
            'IsPlayerConnected': grpc.unary_unary_rpc_method_handler(
                    servicer.IsPlayerConnected,
                    request_deserializer=alpha__pb2.PlayerID.FromString,
                    response_serializer=alpha__pb2.Bool.SerializeToString,
            ),
            'GetConnectedPlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedPlayers,
                    request_deserializer=alpha__pb2.Empty.FromString,
                    response_serializer=alpha__pb2.PlayerIDList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agones.dev.sdk.alpha.SDK', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agones.dev.sdk.alpha.SDK', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SDK(object):
    """SDK service to be used in the GameServer SDK to the Pod Sidecar.
    """

    @staticmethod
    def PlayerConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.alpha.SDK/PlayerConnect',
            alpha__pb2.PlayerID.SerializeToString,
            alpha__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayerDisconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.alpha.SDK/PlayerDisconnect',
            alpha__pb2.PlayerID.SerializeToString,
            alpha__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPlayerCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.alpha.SDK/SetPlayerCapacity',
            alpha__pb2.Count.SerializeToString,
            alpha__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayerCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.alpha.SDK/GetPlayerCapacity',
            alpha__pb2.Empty.SerializeToString,
            alpha__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayerCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.alpha.SDK/GetPlayerCount',
            alpha__pb2.Empty.SerializeToString,
            alpha__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsPlayerConnected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.alpha.SDK/IsPlayerConnected',
            alpha__pb2.PlayerID.SerializeToString,
            alpha__pb2.Bool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectedPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agones.dev.sdk.alpha.SDK/GetConnectedPlayers',
            alpha__pb2.Empty.SerializeToString,
            alpha__pb2.PlayerIDList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)